// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/testing/testing.proto

package testing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusGetRequest_Code int32

const (
	StatusGetRequest_OK                  StatusGetRequest_Code = 0
	StatusGetRequest_CANCELED            StatusGetRequest_Code = 1
	StatusGetRequest_UNKNOWN             StatusGetRequest_Code = 2
	StatusGetRequest_INVALIDARGUMENT     StatusGetRequest_Code = 3
	StatusGetRequest_DEADLINE_EXCEEDED   StatusGetRequest_Code = 4
	StatusGetRequest_NOT_FOUND           StatusGetRequest_Code = 5
	StatusGetRequest_ALREADY_EXISTS      StatusGetRequest_Code = 6
	StatusGetRequest_PERMISSION_DENIED   StatusGetRequest_Code = 7
	StatusGetRequest_RESOURCE_EXHAUSTED  StatusGetRequest_Code = 8
	StatusGetRequest_FAILED_PRECONDITION StatusGetRequest_Code = 9
	StatusGetRequest_ABORTED             StatusGetRequest_Code = 10
	StatusGetRequest_OUT_OF_RANGE        StatusGetRequest_Code = 11
	StatusGetRequest_UNIMPLEMENTED       StatusGetRequest_Code = 12
	StatusGetRequest_INTERNAL            StatusGetRequest_Code = 13
	StatusGetRequest_UNAVAILABLE         StatusGetRequest_Code = 14
	StatusGetRequest_DATALOSS            StatusGetRequest_Code = 15
	StatusGetRequest_UNAUTHENTICATED     StatusGetRequest_Code = 16
)

var StatusGetRequest_Code_name = map[int32]string{
	0:  "OK",
	1:  "CANCELED",
	2:  "UNKNOWN",
	3:  "INVALIDARGUMENT",
	4:  "DEADLINE_EXCEEDED",
	5:  "NOT_FOUND",
	6:  "ALREADY_EXISTS",
	7:  "PERMISSION_DENIED",
	8:  "RESOURCE_EXHAUSTED",
	9:  "FAILED_PRECONDITION",
	10: "ABORTED",
	11: "OUT_OF_RANGE",
	12: "UNIMPLEMENTED",
	13: "INTERNAL",
	14: "UNAVAILABLE",
	15: "DATALOSS",
	16: "UNAUTHENTICATED",
}

var StatusGetRequest_Code_value = map[string]int32{
	"OK":                  0,
	"CANCELED":            1,
	"UNKNOWN":             2,
	"INVALIDARGUMENT":     3,
	"DEADLINE_EXCEEDED":   4,
	"NOT_FOUND":           5,
	"ALREADY_EXISTS":      6,
	"PERMISSION_DENIED":   7,
	"RESOURCE_EXHAUSTED":  8,
	"FAILED_PRECONDITION": 9,
	"ABORTED":             10,
	"OUT_OF_RANGE":        11,
	"UNIMPLEMENTED":       12,
	"INTERNAL":            13,
	"UNAVAILABLE":         14,
	"DATALOSS":            15,
	"UNAUTHENTICATED":     16,
}

func (x StatusGetRequest_Code) String() string {
	return proto.EnumName(StatusGetRequest_Code_name, int32(x))
}

func (StatusGetRequest_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{0, 0}
}

type DetailGetRequest_Code int32

const (
	DetailGetRequest_OK                   DetailGetRequest_Code = 0
	DetailGetRequest_RETRY_INFO           DetailGetRequest_Code = 1
	DetailGetRequest_DEBUG_INFO           DetailGetRequest_Code = 2
	DetailGetRequest_QUOTA_FAILURE        DetailGetRequest_Code = 3
	DetailGetRequest_ERROR_INFO           DetailGetRequest_Code = 4
	DetailGetRequest_PRECONDITION_FAILURE DetailGetRequest_Code = 5
	DetailGetRequest_BAD_REQUEST          DetailGetRequest_Code = 6
	DetailGetRequest_REQUEST_INFO         DetailGetRequest_Code = 7
	DetailGetRequest_RESOURCE_INFO        DetailGetRequest_Code = 8
	DetailGetRequest_HELP                 DetailGetRequest_Code = 9
	DetailGetRequest_LOCALIZED_MESSAGE    DetailGetRequest_Code = 10
	DetailGetRequest_COMBINED_ALL         DetailGetRequest_Code = 20
)

var DetailGetRequest_Code_name = map[int32]string{
	0:  "OK",
	1:  "RETRY_INFO",
	2:  "DEBUG_INFO",
	3:  "QUOTA_FAILURE",
	4:  "ERROR_INFO",
	5:  "PRECONDITION_FAILURE",
	6:  "BAD_REQUEST",
	7:  "REQUEST_INFO",
	8:  "RESOURCE_INFO",
	9:  "HELP",
	10: "LOCALIZED_MESSAGE",
	20: "COMBINED_ALL",
}

var DetailGetRequest_Code_value = map[string]int32{
	"OK":                   0,
	"RETRY_INFO":           1,
	"DEBUG_INFO":           2,
	"QUOTA_FAILURE":        3,
	"ERROR_INFO":           4,
	"PRECONDITION_FAILURE": 5,
	"BAD_REQUEST":          6,
	"REQUEST_INFO":         7,
	"RESOURCE_INFO":        8,
	"HELP":                 9,
	"LOCALIZED_MESSAGE":    10,
	"COMBINED_ALL":         20,
}

func (x DetailGetRequest_Code) String() string {
	return proto.EnumName(DetailGetRequest_Code_name, int32(x))
}

func (DetailGetRequest_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{2, 0}
}

type SetRequest_HealthCheckStatus int32

const (
	SetRequest_UNKNOWN         SetRequest_HealthCheckStatus = 0
	SetRequest_SERVING         SetRequest_HealthCheckStatus = 1
	SetRequest_NOT_SERVING     SetRequest_HealthCheckStatus = 2
	SetRequest_SERVICE_UNKNOWN SetRequest_HealthCheckStatus = 3
)

var SetRequest_HealthCheckStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
	3: "SERVICE_UNKNOWN",
}

var SetRequest_HealthCheckStatus_value = map[string]int32{
	"UNKNOWN":         0,
	"SERVING":         1,
	"NOT_SERVING":     2,
	"SERVICE_UNKNOWN": 3,
}

func (x SetRequest_HealthCheckStatus) String() string {
	return proto.EnumName(SetRequest_HealthCheckStatus_name, int32(x))
}

func (SetRequest_HealthCheckStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{5, 0}
}

type StatusGetRequest struct {
	Code                 StatusGetRequest_Code `protobuf:"varint,1,opt,name=code,proto3,enum=testing.StatusGetRequest_Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StatusGetRequest) Reset()         { *m = StatusGetRequest{} }
func (m *StatusGetRequest) String() string { return proto.CompactTextString(m) }
func (*StatusGetRequest) ProtoMessage()    {}
func (*StatusGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{0}
}

func (m *StatusGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusGetRequest.Unmarshal(m, b)
}
func (m *StatusGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusGetRequest.Marshal(b, m, deterministic)
}
func (m *StatusGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusGetRequest.Merge(m, src)
}
func (m *StatusGetRequest) XXX_Size() int {
	return xxx_messageInfo_StatusGetRequest.Size(m)
}
func (m *StatusGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusGetRequest proto.InternalMessageInfo

func (m *StatusGetRequest) GetCode() StatusGetRequest_Code {
	if m != nil {
		return m.Code
	}
	return StatusGetRequest_OK
}

type StatusGetResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusGetResponse) Reset()         { *m = StatusGetResponse{} }
func (m *StatusGetResponse) String() string { return proto.CompactTextString(m) }
func (*StatusGetResponse) ProtoMessage()    {}
func (*StatusGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{1}
}

func (m *StatusGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusGetResponse.Unmarshal(m, b)
}
func (m *StatusGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusGetResponse.Marshal(b, m, deterministic)
}
func (m *StatusGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusGetResponse.Merge(m, src)
}
func (m *StatusGetResponse) XXX_Size() int {
	return xxx_messageInfo_StatusGetResponse.Size(m)
}
func (m *StatusGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusGetResponse proto.InternalMessageInfo

func (m *StatusGetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DetailGetRequest struct {
	Code                 DetailGetRequest_Code `protobuf:"varint,1,opt,name=code,proto3,enum=testing.DetailGetRequest_Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DetailGetRequest) Reset()         { *m = DetailGetRequest{} }
func (m *DetailGetRequest) String() string { return proto.CompactTextString(m) }
func (*DetailGetRequest) ProtoMessage()    {}
func (*DetailGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{2}
}

func (m *DetailGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailGetRequest.Unmarshal(m, b)
}
func (m *DetailGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailGetRequest.Marshal(b, m, deterministic)
}
func (m *DetailGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailGetRequest.Merge(m, src)
}
func (m *DetailGetRequest) XXX_Size() int {
	return xxx_messageInfo_DetailGetRequest.Size(m)
}
func (m *DetailGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailGetRequest proto.InternalMessageInfo

func (m *DetailGetRequest) GetCode() DetailGetRequest_Code {
	if m != nil {
		return m.Code
	}
	return DetailGetRequest_OK
}

type DetailGetResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailGetResponse) Reset()         { *m = DetailGetResponse{} }
func (m *DetailGetResponse) String() string { return proto.CompactTextString(m) }
func (*DetailGetResponse) ProtoMessage()    {}
func (*DetailGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{3}
}

func (m *DetailGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailGetResponse.Unmarshal(m, b)
}
func (m *DetailGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailGetResponse.Marshal(b, m, deterministic)
}
func (m *DetailGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailGetResponse.Merge(m, src)
}
func (m *DetailGetResponse) XXX_Size() int {
	return xxx_messageInfo_DetailGetResponse.Size(m)
}
func (m *DetailGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailGetResponse proto.InternalMessageInfo

func (m *DetailGetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type MetadataGetResponse struct {
	Metadata             []*MetadataGetResponse_Entry `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MetadataGetResponse) Reset()         { *m = MetadataGetResponse{} }
func (m *MetadataGetResponse) String() string { return proto.CompactTextString(m) }
func (*MetadataGetResponse) ProtoMessage()    {}
func (*MetadataGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{4}
}

func (m *MetadataGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataGetResponse.Unmarshal(m, b)
}
func (m *MetadataGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataGetResponse.Marshal(b, m, deterministic)
}
func (m *MetadataGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataGetResponse.Merge(m, src)
}
func (m *MetadataGetResponse) XXX_Size() int {
	return xxx_messageInfo_MetadataGetResponse.Size(m)
}
func (m *MetadataGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataGetResponse proto.InternalMessageInfo

func (m *MetadataGetResponse) GetMetadata() []*MetadataGetResponse_Entry {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type MetadataGetResponse_Entry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataGetResponse_Entry) Reset()         { *m = MetadataGetResponse_Entry{} }
func (m *MetadataGetResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*MetadataGetResponse_Entry) ProtoMessage()    {}
func (*MetadataGetResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{4, 0}
}

func (m *MetadataGetResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataGetResponse_Entry.Unmarshal(m, b)
}
func (m *MetadataGetResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataGetResponse_Entry.Marshal(b, m, deterministic)
}
func (m *MetadataGetResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataGetResponse_Entry.Merge(m, src)
}
func (m *MetadataGetResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_MetadataGetResponse_Entry.Size(m)
}
func (m *MetadataGetResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataGetResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataGetResponse_Entry proto.InternalMessageInfo

func (m *MetadataGetResponse_Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MetadataGetResponse_Entry) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetRequest struct {
	Status               SetRequest_HealthCheckStatus `protobuf:"varint,1,opt,name=status,proto3,enum=testing.SetRequest_HealthCheckStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d94c77bda79ee8c3, []int{5}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetStatus() SetRequest_HealthCheckStatus {
	if m != nil {
		return m.Status
	}
	return SetRequest_UNKNOWN
}

func init() {
	proto.RegisterEnum("testing.StatusGetRequest_Code", StatusGetRequest_Code_name, StatusGetRequest_Code_value)
	proto.RegisterEnum("testing.DetailGetRequest_Code", DetailGetRequest_Code_name, DetailGetRequest_Code_value)
	proto.RegisterEnum("testing.SetRequest_HealthCheckStatus", SetRequest_HealthCheckStatus_name, SetRequest_HealthCheckStatus_value)
	proto.RegisterType((*StatusGetRequest)(nil), "testing.StatusGetRequest")
	proto.RegisterType((*StatusGetResponse)(nil), "testing.StatusGetResponse")
	proto.RegisterType((*DetailGetRequest)(nil), "testing.DetailGetRequest")
	proto.RegisterType((*DetailGetResponse)(nil), "testing.DetailGetResponse")
	proto.RegisterType((*MetadataGetResponse)(nil), "testing.MetadataGetResponse")
	proto.RegisterType((*MetadataGetResponse_Entry)(nil), "testing.MetadataGetResponse.Entry")
	proto.RegisterType((*SetRequest)(nil), "testing.SetRequest")
}

func init() { proto.RegisterFile("internal/testing/testing.proto", fileDescriptor_d94c77bda79ee8c3) }

var fileDescriptor_d94c77bda79ee8c3 = []byte{
	// 798 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x4e, 0x23, 0x37,
	0x14, 0xde, 0x49, 0x42, 0x48, 0x0e, 0x7f, 0xc6, 0xd0, 0x2d, 0x4d, 0xab, 0x15, 0x8a, 0xb4, 0x12,
	0x37, 0x9b, 0x48, 0xe9, 0x55, 0x45, 0x5b, 0xc9, 0x19, 0x9f, 0x24, 0xd6, 0x4e, 0x6c, 0xd6, 0x33,
	0x43, 0x77, 0xf7, 0x66, 0x34, 0x80, 0x1b, 0x10, 0x21, 0xa1, 0xc4, 0xa9, 0xca, 0x0b, 0xf4, 0x2d,
	0x2a, 0xf5, 0x21, 0xfa, 0x28, 0x7d, 0x9d, 0x4a, 0x95, 0x67, 0x32, 0x10, 0x05, 0xa8, 0x7a, 0x35,
	0x73, 0x8e, 0xbf, 0xf3, 0xd9, 0xfe, 0x3e, 0x9f, 0x03, 0x6f, 0xae, 0x26, 0xd6, 0xdc, 0x4d, 0xd2,
	0x71, 0xdb, 0x9a, 0x99, 0xbd, 0x9a, 0x8c, 0x8a, 0x6f, 0xeb, 0xf6, 0x6e, 0x6a, 0xa7, 0x74, 0x7d,
	0x11, 0x36, 0xbe, 0x1e, 0x4d, 0xa7, 0xa3, 0xb1, 0x69, 0x67, 0xe9, 0xb3, 0xf9, 0xcf, 0x6d, 0x73,
	0x73, 0x6b, 0xef, 0x73, 0x54, 0xf3, 0x9f, 0x12, 0x90, 0xd0, 0xa6, 0x76, 0x3e, 0xeb, 0x1b, 0xab,
	0xcd, 0x2f, 0x73, 0x33, 0xb3, 0xb4, 0x03, 0x95, 0xf3, 0xe9, 0x85, 0x39, 0xf0, 0x0e, 0xbd, 0xa3,
	0xed, 0xce, 0x9b, 0x56, 0x41, 0xbc, 0x0a, 0x6c, 0xf9, 0xd3, 0x0b, 0xa3, 0x33, 0x6c, 0xf3, 0xaf,
	0x12, 0x54, 0x5c, 0x48, 0xab, 0x50, 0x52, 0xef, 0xc9, 0x2b, 0xba, 0x09, 0x35, 0x9f, 0x49, 0x1f,
	0x03, 0xe4, 0xc4, 0xa3, 0x1b, 0xb0, 0x1e, 0xcb, 0xf7, 0x52, 0xfd, 0x24, 0x49, 0x89, 0xee, 0xc1,
	0x8e, 0x90, 0xa7, 0x2c, 0x10, 0x9c, 0xe9, 0x7e, 0x3c, 0x44, 0x19, 0x91, 0x32, 0xfd, 0x02, 0x76,
	0x39, 0x32, 0x1e, 0x08, 0x89, 0x09, 0x7e, 0xf4, 0x11, 0x39, 0x72, 0x52, 0xa1, 0x5b, 0x50, 0x97,
	0x2a, 0x4a, 0x7a, 0x2a, 0x96, 0x9c, 0xac, 0x51, 0x0a, 0xdb, 0x2c, 0xd0, 0xc8, 0xf8, 0xa7, 0x04,
	0x3f, 0x8a, 0x30, 0x0a, 0x49, 0xd5, 0x55, 0x9e, 0xa0, 0x1e, 0x8a, 0x30, 0x14, 0x4a, 0x26, 0x1c,
	0xa5, 0x40, 0x4e, 0xd6, 0xe9, 0x6b, 0xa0, 0x1a, 0x43, 0x15, 0x6b, 0xdf, 0x11, 0x0e, 0x58, 0x1c,
	0x46, 0xc8, 0x49, 0x8d, 0x7e, 0x09, 0x7b, 0x3d, 0x26, 0x02, 0xe4, 0xc9, 0x89, 0x46, 0x5f, 0x49,
	0x2e, 0x22, 0xa1, 0x24, 0xa9, 0xbb, 0x33, 0xb2, 0xae, 0xd2, 0x0e, 0x05, 0x94, 0xc0, 0xa6, 0x8a,
	0xa3, 0x44, 0xf5, 0x12, 0xcd, 0x64, 0x1f, 0xc9, 0x06, 0xdd, 0x85, 0xad, 0x58, 0x8a, 0xe1, 0x49,
	0x80, 0xee, 0xc4, 0xc8, 0xc9, 0xa6, 0xbb, 0xa3, 0x90, 0x11, 0x6a, 0xc9, 0x02, 0xb2, 0x45, 0x77,
	0x60, 0x23, 0x96, 0xec, 0x94, 0x89, 0x80, 0x75, 0x03, 0x24, 0xdb, 0x6e, 0x99, 0xb3, 0x88, 0x05,
	0x2a, 0x0c, 0xc9, 0x8e, 0xbb, 0x75, 0x2c, 0x59, 0x1c, 0x0d, 0x50, 0x46, 0xc2, 0x67, 0x8e, 0x81,
	0x34, 0xdf, 0xc2, 0xee, 0x92, 0xaa, 0xb3, 0xdb, 0xe9, 0x64, 0x66, 0x28, 0x81, 0xf2, 0xcd, 0x6c,
	0x94, 0xc9, 0x5f, 0xd7, 0xee, 0xb7, 0xf9, 0x47, 0x09, 0x08, 0x37, 0x36, 0xbd, 0x1a, 0xff, 0x0f,
	0x9b, 0x56, 0x81, 0xcb, 0x36, 0xfd, 0xed, 0xad, 0xd8, 0xb4, 0x0d, 0xa0, 0x31, 0xd2, 0x9f, 0x12,
	0x21, 0x7b, 0x8a, 0x78, 0x2e, 0xe6, 0xd8, 0x8d, 0xfb, 0x79, 0x5c, 0x72, 0xb7, 0xfe, 0x10, 0xab,
	0x88, 0x25, 0x4e, 0xb3, 0x58, 0x23, 0x29, 0x3b, 0x08, 0x6a, 0xad, 0x74, 0x0e, 0xa9, 0xd0, 0x03,
	0xd8, 0x5f, 0x56, 0xf2, 0x01, 0xb9, 0xe6, 0x14, 0xe9, 0x32, 0x9e, 0x68, 0xfc, 0x10, 0x63, 0x18,
	0x91, 0xaa, 0x53, 0x75, 0x11, 0xe4, 0xc5, 0xeb, 0x8e, 0xff, 0xc1, 0xa5, 0x2c, 0x55, 0xa3, 0x35,
	0xa8, 0x0c, 0x30, 0x38, 0x21, 0x75, 0xe7, 0x6c, 0xa0, 0x7c, 0x16, 0x88, 0xcf, 0xc8, 0x93, 0x21,
	0x86, 0x21, 0xeb, 0x63, 0xee, 0x8d, 0xaf, 0x86, 0x5d, 0x21, 0x91, 0x27, 0x2c, 0x08, 0xc8, 0xbe,
	0x93, 0x71, 0xe9, 0xd6, 0x2f, 0xca, 0xf8, 0xbb, 0x07, 0x7b, 0x43, 0x63, 0xd3, 0x8b, 0xd4, 0xa6,
	0xcb, 0xc8, 0x1f, 0xa1, 0x76, 0xb3, 0x48, 0x1f, 0x78, 0x87, 0xe5, 0xa3, 0x8d, 0x4e, 0xf3, 0x41,
	0xcd, 0x67, 0xf0, 0x2d, 0x9c, 0xd8, 0xbb, 0x7b, 0xfd, 0x50, 0xd3, 0x68, 0xc3, 0x5a, 0x96, 0x72,
	0x5b, 0x5e, 0x9b, 0xfb, 0x62, 0xcb, 0x6b, 0x73, 0x4f, 0xf7, 0x61, 0xed, 0xd7, 0x74, 0x3c, 0x37,
	0x07, 0xa5, 0xc3, 0xf2, 0x51, 0x5d, 0xe7, 0x41, 0xf3, 0x4f, 0x0f, 0x20, 0x7c, 0x74, 0xf2, 0x07,
	0xa8, 0xce, 0xb2, 0x57, 0xb0, 0xf0, 0xf2, 0xed, 0x63, 0xcb, 0x3d, 0xba, 0x38, 0x30, 0xe9, 0xd8,
	0x5e, 0xfa, 0x97, 0xe6, 0xfc, 0x3a, 0x7f, 0x32, 0x7a, 0x51, 0xd4, 0x0c, 0x61, 0xf7, 0xc9, 0xe2,
	0x72, 0xc7, 0xbd, 0x72, 0x41, 0x88, 0xfa, 0x54, 0xc8, 0x3e, 0xf1, 0x9c, 0x2b, 0xae, 0xa5, 0x8a,
	0x44, 0xd6, 0x8f, 0x59, 0xe0, 0x63, 0x52, 0x94, 0x94, 0x3b, 0x3d, 0xa8, 0x2e, 0x98, 0xbe, 0x87,
	0x72, 0xdf, 0x58, 0xfa, 0xd5, 0x8b, 0x73, 0xa0, 0xd1, 0x78, 0x6e, 0x29, 0xd7, 0xca, 0xf1, 0xe4,
	0xd6, 0x3c, 0xe5, 0x59, 0x7d, 0xa8, 0x4b, 0x3c, 0x4f, 0xdc, 0xec, 0xf4, 0xa1, 0x56, 0x58, 0x41,
	0x8f, 0x73, 0xa6, 0xd7, 0xad, 0x7c, 0xb4, 0xb5, 0x8a, 0xd1, 0xd6, 0x42, 0x37, 0xda, 0x1a, 0xdf,
	0xfc, 0x97, 0x79, 0x9d, 0x2e, 0x6c, 0xfa, 0x97, 0xe9, 0x64, 0x64, 0x72, 0xcd, 0x68, 0x07, 0xca,
	0xa1, 0xb1, 0x74, 0xef, 0x19, 0xcd, 0x1b, 0x2f, 0xec, 0xd0, 0x3d, 0xfe, 0xfc, 0xdd, 0xe8, 0xca,
	0x5e, 0xce, 0xcf, 0x5a, 0xe7, 0xd3, 0x9b, 0xb6, 0x6b, 0xa8, 0x77, 0x03, 0xf3, 0x5b, 0x31, 0x81,
	0xdf, 0x8d, 0xee, 0x6e, 0xcf, 0xdb, 0xab, 0xf3, 0xf9, 0x78, 0xf1, 0x3d, 0xab, 0x66, 0x64, 0xdf,
	0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x85, 0x47, 0x27, 0x1c, 0xc2, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatusClient is the client API for Status service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatusClient interface {
	Get(ctx context.Context, in *StatusGetRequest, opts ...grpc.CallOption) (*StatusGetResponse, error)
}

type statusClient struct {
	cc *grpc.ClientConn
}

func NewStatusClient(cc *grpc.ClientConn) StatusClient {
	return &statusClient{cc}
}

func (c *statusClient) Get(ctx context.Context, in *StatusGetRequest, opts ...grpc.CallOption) (*StatusGetResponse, error) {
	out := new(StatusGetResponse)
	err := c.cc.Invoke(ctx, "/testing.Status/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusServer is the server API for Status service.
type StatusServer interface {
	Get(context.Context, *StatusGetRequest) (*StatusGetResponse, error)
}

// UnimplementedStatusServer can be embedded to have forward compatible implementations.
type UnimplementedStatusServer struct {
}

func (*UnimplementedStatusServer) Get(ctx context.Context, req *StatusGetRequest) (*StatusGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterStatusServer(s *grpc.Server, srv StatusServer) {
	s.RegisterService(&_Status_serviceDesc, srv)
}

func _Status_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testing.Status/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).Get(ctx, req.(*StatusGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Status_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testing.Status",
	HandlerType: (*StatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Status_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/testing/testing.proto",
}

// DetailClient is the client API for Detail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DetailClient interface {
	Get(ctx context.Context, in *DetailGetRequest, opts ...grpc.CallOption) (*DetailGetResponse, error)
}

type detailClient struct {
	cc *grpc.ClientConn
}

func NewDetailClient(cc *grpc.ClientConn) DetailClient {
	return &detailClient{cc}
}

func (c *detailClient) Get(ctx context.Context, in *DetailGetRequest, opts ...grpc.CallOption) (*DetailGetResponse, error) {
	out := new(DetailGetResponse)
	err := c.cc.Invoke(ctx, "/testing.Detail/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetailServer is the server API for Detail service.
type DetailServer interface {
	Get(context.Context, *DetailGetRequest) (*DetailGetResponse, error)
}

// UnimplementedDetailServer can be embedded to have forward compatible implementations.
type UnimplementedDetailServer struct {
}

func (*UnimplementedDetailServer) Get(ctx context.Context, req *DetailGetRequest) (*DetailGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterDetailServer(s *grpc.Server, srv DetailServer) {
	s.RegisterService(&_Detail_serviceDesc, srv)
}

func _Detail_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetailServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testing.Detail/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetailServer).Get(ctx, req.(*DetailGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Detail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testing.Detail",
	HandlerType: (*DetailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Detail_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/testing/testing.proto",
}

// MetadataClient is the client API for Metadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataClient interface {
	Get(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MetadataGetResponse, error)
}

type metadataClient struct {
	cc *grpc.ClientConn
}

func NewMetadataClient(cc *grpc.ClientConn) MetadataClient {
	return &metadataClient{cc}
}

func (c *metadataClient) Get(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MetadataGetResponse, error) {
	out := new(MetadataGetResponse)
	err := c.cc.Invoke(ctx, "/testing.Metadata/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServer is the server API for Metadata service.
type MetadataServer interface {
	Get(context.Context, *empty.Empty) (*MetadataGetResponse, error)
}

// UnimplementedMetadataServer can be embedded to have forward compatible implementations.
type UnimplementedMetadataServer struct {
}

func (*UnimplementedMetadataServer) Get(ctx context.Context, req *empty.Empty) (*MetadataGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterMetadataServer(s *grpc.Server, srv MetadataServer) {
	s.RegisterService(&_Metadata_serviceDesc, srv)
}

func _Metadata_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testing.Metadata/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServer).Get(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metadata_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testing.Metadata",
	HandlerType: (*MetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Metadata_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/testing/testing.proto",
}

// ChangeHealthClient is the client API for ChangeHealth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChangeHealthClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type changeHealthClient struct {
	cc *grpc.ClientConn
}

func NewChangeHealthClient(cc *grpc.ClientConn) ChangeHealthClient {
	return &changeHealthClient{cc}
}

func (c *changeHealthClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/testing.ChangeHealth/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChangeHealthServer is the server API for ChangeHealth service.
type ChangeHealthServer interface {
	Set(context.Context, *SetRequest) (*empty.Empty, error)
}

// UnimplementedChangeHealthServer can be embedded to have forward compatible implementations.
type UnimplementedChangeHealthServer struct {
}

func (*UnimplementedChangeHealthServer) Set(ctx context.Context, req *SetRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}

func RegisterChangeHealthServer(s *grpc.Server, srv ChangeHealthServer) {
	s.RegisterService(&_ChangeHealth_serviceDesc, srv)
}

func _ChangeHealth_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeHealthServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testing.ChangeHealth/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeHealthServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChangeHealth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testing.ChangeHealth",
	HandlerType: (*ChangeHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _ChangeHealth_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/testing/testing.proto",
}
