// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/test/test.proto

package test

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Code int32

const (
	Code_OK                  Code = 0
	Code_CANCELED            Code = 1
	Code_UNKNOWN             Code = 2
	Code_INVALIDARGUMENT     Code = 3
	Code_DEADLINE_EXCEEDED   Code = 4
	Code_NOT_FOUND           Code = 5
	Code_ALREADY_EXISTS      Code = 6
	Code_PERMISSION_DENIED   Code = 7
	Code_RESOURCE_EXHAUSTED  Code = 8
	Code_FAILED_PRECONDITION Code = 9
	Code_ABORTED             Code = 10
	Code_OUT_OF_RANGE        Code = 11
	Code_UNIMPLEMENTED       Code = 12
	Code_INTERNAL            Code = 13
	Code_UNAVAILABLE         Code = 14
	Code_DATALOSS            Code = 15
	Code_UNAUTHENTICATED     Code = 16
)

var Code_name = map[int32]string{
	0:  "OK",
	1:  "CANCELED",
	2:  "UNKNOWN",
	3:  "INVALIDARGUMENT",
	4:  "DEADLINE_EXCEEDED",
	5:  "NOT_FOUND",
	6:  "ALREADY_EXISTS",
	7:  "PERMISSION_DENIED",
	8:  "RESOURCE_EXHAUSTED",
	9:  "FAILED_PRECONDITION",
	10: "ABORTED",
	11: "OUT_OF_RANGE",
	12: "UNIMPLEMENTED",
	13: "INTERNAL",
	14: "UNAVAILABLE",
	15: "DATALOSS",
	16: "UNAUTHENTICATED",
}

var Code_value = map[string]int32{
	"OK":                  0,
	"CANCELED":            1,
	"UNKNOWN":             2,
	"INVALIDARGUMENT":     3,
	"DEADLINE_EXCEEDED":   4,
	"NOT_FOUND":           5,
	"ALREADY_EXISTS":      6,
	"PERMISSION_DENIED":   7,
	"RESOURCE_EXHAUSTED":  8,
	"FAILED_PRECONDITION": 9,
	"ABORTED":             10,
	"OUT_OF_RANGE":        11,
	"UNIMPLEMENTED":       12,
	"INTERNAL":            13,
	"UNAVAILABLE":         14,
	"DATALOSS":            15,
	"UNAUTHENTICATED":     16,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa39e6c173e89b60, []int{0}
}

type GetRequest struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=test.Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa39e6c173e89b60, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_OK
}

type GetResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa39e6c173e89b60, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("test.Code", Code_name, Code_value)
	proto.RegisterType((*GetRequest)(nil), "test.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "test.GetResponse")
}

func init() { proto.RegisterFile("internal/test/test.proto", fileDescriptor_fa39e6c173e89b60) }

var fileDescriptor_fa39e6c173e89b60 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x6f, 0x13, 0x31,
	0x10, 0xc5, 0xc9, 0x1f, 0xd2, 0x66, 0xf2, 0xcf, 0x71, 0x05, 0x54, 0x1c, 0x00, 0xf5, 0x84, 0x2a,
	0x9a, 0x48, 0x2d, 0x9c, 0x38, 0x39, 0xeb, 0x49, 0x62, 0x75, 0x33, 0x8e, 0xbc, 0x76, 0x29, 0x5c,
	0x56, 0x6d, 0x6a, 0x85, 0x48, 0x34, 0x1b, 0xb2, 0x8e, 0xc4, 0x07, 0xe3, 0x03, 0x22, 0x6f, 0x0f,
	0xc0, 0x65, 0x34, 0x1a, 0xff, 0x3c, 0x9a, 0xf7, 0x1e, 0x9c, 0x6e, 0xb6, 0xc1, 0xef, 0xb7, 0x77,
	0x3f, 0xc6, 0xc1, 0x97, 0xa1, 0x2a, 0xa3, 0xdd, 0xbe, 0x08, 0x05, 0x6f, 0xc6, 0xfe, 0xec, 0x03,
	0xc0, 0xcc, 0x07, 0xe3, 0x7f, 0x1e, 0x7c, 0x19, 0xf8, 0x1b, 0x68, 0xae, 0x8a, 0x07, 0x7f, 0x5a,
	0x7b, 0x57, 0x7b, 0xdf, 0xbf, 0x84, 0x51, 0x85, 0x27, 0xc5, 0x83, 0x37, 0xd5, 0xfc, 0xec, 0x2d,
	0x74, 0x2a, 0xba, 0xdc, 0x15, 0xdb, 0xd2, 0x73, 0x06, 0x8d, 0xc7, 0x72, 0x5d, 0xd1, 0x6d, 0x13,
	0xdb, 0xf3, 0xdf, 0x75, 0x68, 0x46, 0x9e, 0xb7, 0xa0, 0xae, 0xaf, 0xd9, 0x33, 0xde, 0x85, 0xe3,
	0x44, 0x50, 0x82, 0x29, 0x4a, 0x56, 0xe3, 0x1d, 0x38, 0x72, 0x74, 0x4d, 0xfa, 0x0b, 0xb1, 0x3a,
	0x3f, 0x81, 0x81, 0xa2, 0x1b, 0x91, 0x2a, 0x29, 0xcc, 0xcc, 0x2d, 0x90, 0x2c, 0x6b, 0xf0, 0x17,
	0x30, 0x94, 0x28, 0x64, 0xaa, 0x08, 0x73, 0xbc, 0x4d, 0x10, 0x25, 0x4a, 0xd6, 0xe4, 0x3d, 0x68,
	0x93, 0xb6, 0xf9, 0x54, 0x3b, 0x92, 0xec, 0x39, 0xe7, 0xd0, 0x17, 0xa9, 0x41, 0x21, 0xbf, 0xe6,
	0x78, 0xab, 0x32, 0x9b, 0xb1, 0x56, 0xfc, 0xb9, 0x44, 0xb3, 0x50, 0x59, 0xa6, 0x34, 0xe5, 0x12,
	0x49, 0xa1, 0x64, 0x47, 0xfc, 0x25, 0x70, 0x83, 0x99, 0x76, 0x26, 0x89, 0x0b, 0xe7, 0xc2, 0x65,
	0x16, 0x25, 0x3b, 0xe6, 0xaf, 0xe0, 0x64, 0x2a, 0x54, 0x8a, 0x32, 0x5f, 0x1a, 0x4c, 0x34, 0x49,
	0x65, 0x95, 0x26, 0xd6, 0x8e, 0x37, 0x8a, 0x89, 0x36, 0x91, 0x02, 0xce, 0xa0, 0xab, 0x9d, 0xcd,
	0xf5, 0x34, 0x37, 0x82, 0x66, 0xc8, 0x3a, 0x7c, 0x08, 0x3d, 0x47, 0x6a, 0xb1, 0x4c, 0x31, 0x5e,
	0x8c, 0x92, 0x75, 0xa3, 0x46, 0x45, 0x16, 0x0d, 0x89, 0x94, 0xf5, 0xf8, 0x00, 0x3a, 0x8e, 0xc4,
	0x8d, 0x50, 0xa9, 0x98, 0xa4, 0xc8, 0xfa, 0xf1, 0x59, 0x0a, 0x2b, 0x52, 0x9d, 0x65, 0x6c, 0x10,
	0x55, 0x3b, 0x12, 0xce, 0xce, 0x91, 0xac, 0x4a, 0x44, 0xdc, 0xc0, 0x2e, 0x3f, 0x42, 0x2b, 0x0b,
	0x77, 0xe1, 0x50, 0xf2, 0x73, 0x68, 0xcc, 0x7c, 0xe0, 0xec, 0xc9, 0xfa, 0xbf, 0xd1, 0xbc, 0x1e,
	0xfe, 0x33, 0x79, 0xb2, 0x7f, 0xf2, 0xe9, 0xdb, 0xd5, 0x7a, 0x13, 0xbe, 0x1f, 0xee, 0x47, 0xab,
	0xe2, 0x71, 0x1c, 0x6d, 0xbf, 0x98, 0xfb, 0x5f, 0x55, 0xc6, 0x9b, 0xed, 0xfa, 0x62, 0xbd, 0xdf,
	0xad, 0xc6, 0xff, 0xc5, 0xff, 0x39, 0x96, 0xfb, 0x56, 0x95, 0xff, 0xd5, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1a, 0xec, 0x3f, 0xba, 0x1b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatusClient is the client API for Status service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatusClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type statusClient struct {
	cc *grpc.ClientConn
}

func NewStatusClient(cc *grpc.ClientConn) StatusClient {
	return &statusClient{cc}
}

func (c *statusClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/test.Status/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusServer is the server API for Status service.
type StatusServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedStatusServer can be embedded to have forward compatible implementations.
type UnimplementedStatusServer struct {
}

func (*UnimplementedStatusServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterStatusServer(s *grpc.Server, srv StatusServer) {
	s.RegisterService(&_Status_serviceDesc, srv)
}

func _Status_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.Status/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Status_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.Status",
	HandlerType: (*StatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Status_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/test/test.proto",
}
